# Generated by Django 5.0.7 on 2024-07-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
